version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
    environment:
      - MONGO_USER=***
      - MONGO_PASSWORD=***
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=***
      - MONGO_INITDB_ROOT_USERNAME=***
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: